import Head from "next/head";
import LandingContainer from "@/modules/landing/LandingContainer";

import { Toaster } from 'react-hot-toast'

export default function Home() {
  return (
    <>
      <Head>
        <title>DefiLens</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/next.svg" />
      </Head>
      <Toaster
        position="top-right"
      />
      <LandingContainer />
    </>
  );
}
